create table public.books (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  title text not null,
  author text not null default 'Не указан',
  description text,
  genre text not null default 'Без жанра',
  status text not null default 'Не читано' check (status in ('Читаю', 'Не читано', 'Прочитано', 'Хочу купить')),
  rating smallint check (rating between 1 and 10),
  review text,
  completed_at timestamptz,
  color text not null default '#6b5c93',
  spine text not null default '#d7cdea',
  initials text not null default '',
  cover_image text,
  collections text[] not null default '{}',
  import_source text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index books_user_id_created_at_idx on public.books (user_id, created_at desc);
create index books_user_id_import_source_idx on public.books (user_id, import_source);

alter table public.books enable row level security;

create policy "Users can view their books"
  on public.books for select using ((select auth.uid()) = user_id);

create policy "Users can add their books"
  on public.books for insert with check ((select auth.uid()) = user_id);

create policy "Users can update their books"
  on public.books for update using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

create policy "Users can delete their books"
  on public.books for delete using ((select auth.uid()) = user_id);
