create table public.goals (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  title text not null,
  book_ids bigint[] not null default '{}',
  created_at timestamptz not null default now()
);

create index goals_user_id_idx on public.goals (user_id);

alter table public.goals enable row level security;

create policy "Users can view their goals"
  on public.goals for select using ((select auth.uid()) = user_id);

create policy "Users can add their goals"
  on public.goals for insert with check ((select auth.uid()) = user_id);

create policy "Users can update their goals"
  on public.goals for update using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

create policy "Users can delete their goals"
  on public.goals for delete using ((select auth.uid()) = user_id);
